name: Review Dog
on:
  pull_request:
    branches: [master]

jobs:
  code-lint:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - uses: reviewdog/action-eslint@2fee6dd72a5419ff4113f694e2068d2a03bb35dd
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          reporter: github-pr-check
