name: Unit test
on:
  pull_request:
    branches: [master]

permissions:
  contents: write
  pull-requests: write
  checks: write

jobs:
  unit-test-with-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run unit tests with coverage
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          github-token: ${{ secrets.GH_TOKEN }}
